repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.10.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ "--fix", "--ignore=F403,F405,F811" ]
    # Run the formatter.
    - id: ruff-format
