####### README #######
# This is the HOWTO and the config file to build .qmd files
#
# First install quartodoc with `uv pip install quartodoc`
#
# To create the qmd files, run the following command in the terminal:
# > quartodoc build
# the result will be in ./qmd_files or (else specified in the dir field)
# modify the current file to change the included functions and the layout
# finally, run the following command to preview the website if wanted:
# > quarto preview
# 
# NOTE: This references the marginaleffects in .venv first, to reference the local marginaleffects, delete or rename the folder marginaleffects in .venv/lib/
# Alternatively, you can build the package with `uv build` and then install it in the .venv with `uv pip install dist/marginaleffects[...].whl`


project:
  type: website

# tell quarto to read the generated sidebar
# metadata-files:
#   - _sidebar.yml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: marginaleffects
  style: "pkgdown"
  # write sidebar data to this file
  # sidebar: _sidebar.yml
  dir: qmd_files

  sections:
    - title: Marginaleffects API reference guide
      desc: Marginaleffects functions.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - predictions
        - comparisons
        - slopes
        - hypotheses
        - datagrid
        - plot_predictions
        - plot_comparisons
        - plot_slopes

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
            - griffe_inherited_docstrings
            - docstring_inheritance.griffe
